graph TD
    855b027 --> _idea__gitignore
    855b027 --> _idea_config_2_iml
    855b027 --> _idea_inspectionProfiles_Project_Default_xml
    855b027 --> _idea_inspectionProfiles_profiles_settings_xml
    855b027 --> _idea_misc_xml
    855b027 --> _idea_modules_xml
    855b027 --> _idea_vcs_xml
    855b027 --> config_yaml
    855b027 --> file_1_txt
    855b027 --> file_2_txt
    855b027 --> main_py
    855b027 --> output_graph_mmd